version: '3'

services:
  nginx:
    image: nginx:latest # Replace with your image name
    ports:
      - "185.15.209.234:80:80" # Replace with your desired IP address
    volumes:
      - /home/gts/web-watcher/htmldocs:/usr/share/nginx/html
      - /home/gts/web-watcher/config/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  web-watcher-frontend:
    image: web-watcher-frontend:0.0.1
    build:
      context: ./web_watcher_inspector/ww_frontend/
      dockerfile: Dockerfile
    ports:
      - "185.15.209.234:5000:80"
    restart: always

  web-watcher-backend:
    image: web-watcher-backend:0.0.3
    build:
      context: ./web_watcher_inspector/backend/
      dockerfile: Dockerfile
    ports:
      - "185.15.209.234:8007:80"
    volumes:
      - ./web_watcher_inspector/backend/:/home/gts/code
      - ./web_watcher_inspector/backend/:/home/gts/code
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
